version: 2.1

orbs: 
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
  windows: circleci/windows@2.2.0
  
executors:

jobs:
  build-windows:
    executor:
      name: windows/default
    steps:
      - git-shallow-clone/checkout:
          shell: bash.exe
          fetch_depth: 3
      - run:
          name: List files
          shell: bash.exe
          command: |
            ls -laH
  build-linux:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - git-shallow-clone/checkout:
          fetch_depth: 3
      - run:
          name: List files
          command: |
            ls -laH

workflows:
  main:
    jobs:
      - build-linux
